# Generated by Django 4.1.4 on 2023-07-10 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='author',
            new_name='person',
        ),
    ]
