# Generated by Django 4.1.4 on 2023-07-10 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_author_follow_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
