# Generated by Django 4.1.4 on 2023-07-10 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='user',
            new_name='person',
        ),
    ]
