# Generated by Django 4.1.4 on 2023-07-10 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_user_follow_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
