# Generated by Django 4.1.4 on 2023-07-10 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='person',
            new_name='user',
        ),
    ]
