# Generated by Django 4.1.4 on 2023-07-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_likepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likepost',
            name='username',
            field=models.CharField(max_length=500),
        ),
    ]
