# Generated by Django 4.1.4 on 2023-07-08 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_likepost_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikePost',
        ),
    ]
