# Generated by Django 4.1.4 on 2023-07-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
